### ISSUE TITLE
Expected throw test failed, even if an error occured

### ISSUE THREAD

**Issue by Starmarine3355** [TheNexusAvenger/Nexus-Unit-Testing#11]
![bild](https://user-images.githubusercontent.com/47106566/216767304-fbc14bfd-f543-48a0-a480-cf7d50703e2c.png)

**Comment by TheNexusAvenger** [comment]
I need more information about this. I don't see the problem with the following:
```lua
return function()
	describe("A TestEZ test", function()
		it("should catch errors.", function()
			expect(function() error("Test") end).to.throw()
		end)
	end)
end
```

**Comment by TheNexusAvenger** [comment]
Closing due to a lack of information. Please re-open with more information if this is still a problem.
