### ISSUE TITLE
Print calls in unit tests or tested functions not producing anything in the output window

### ISSUE THREAD

**Issue by psdillon** [TheNexusAvenger/Nexus-Unit-Testing#4]
Not sure if this is a problem with the plugin or Roblox Studio itself, but print calls seem to be suppressed in both the unit testing code and the functions being tested.  This makes it hard to debug failing code.

**Comment by TheNexusAvenger** [comment]
Could you provide your unit test you are running, as well as which runner? If you are using the command line version, this is currently intended but will be addressed in the next release (brought up in https://github.com/TheNexusAvenger/Nexus-Unit-Testing/pull/2). If this is the plugin, make sure you are using opening the output for the test.

**Comment by psdillon** [comment]
I'm using the plugin to run the tests.  Here's the test:

`local NexusUnitTesting = require(game.ServerStorage.Tests.NexusUnitTesting)

local intercept = require(game.ServerStorage.Modules.InterceptModuleScript)

NexusUnitTesting:RegisterUnitTest("TestName1",function(UnitTest)
    UnitTest:AssertEquals(1 + 1,2,"Addition doesn't work.")
end)

NexusUnitTesting:RegisterUnitTest("TestInterceptPositionSolver",function(UnitTest)
	local targetPosition = Vector3:new(120,40,0)
	local targetVelocity = Vector3:new(5,2,0)
	local chaserPosition = Vector3:new(80,80,0)
	local chaserSpeed = 10
	
	
	local interceptPosition = intercept.calculateInterceptPosition(targetPosition, targetVelocity.Magnitude, targetVelocity.Unit, chaserPosition, chaserSpeed)
	
	print("Intercept position = (" .. interceptPosition.X .. "," .. interceptPosition.Y .. "," .. interceptPosition.Z .. ")")
	
	UnitTest:AssertEquals(1,1,"Dummy Fail")
end)

return true`

**Comment by TheNexusAvenger** [comment]
Can you attach a screenshot window of the test output window? This is different from the Roblox Studio output where it is only for the test. To open it, double click on the sub-test in the plugin.

**Comment by psdillon** [comment]
Ah, I did not realize there was a test output window!  Thanks, it's working as described.

![image](https://user-images.githubusercontent.com/3769461/87315563-ed31f900-c567-11ea-8293-4905c7b128ad.png)

**Comment by TheNexusAvenger** [comment]
One thing to note is that sometimes the first line does not appear in the output window. I noticed this before where I would get the stack trace of an error but not the message itself. I will at some point populate that repository (https://github.com/thenexusavenger/nexus-unit-testing-plugin) with the current issues with the plugin.

**Comment by psdillon** [comment]
Thanks very much.  Apologies I could not ask these questions first on the Roblox developer forums as I’m not yet allowed to post there for some reason.

Your plugin is much appreciated!

**Comment by TheNexusAvenger** [comment]
I strongly recommend posting on the GitHub repositories of Roblox projects rather than their developer forum posts. Bug tracking is *much* easier on GitHub than a thread on the developer forum.

**Comment by psdillon** [comment]
I just found that print calls within the functions I'm testing aren't being displayed in either the output window or the test output window.  Is there a way to enable it?

Also, a minor problem: print calls within the test code are being displayed, but the first line is obscured under the test name heading:

![image](https://user-images.githubusercontent.com/3769461/87369842-ce158480-c5c4-11ea-8427-1a2b7cae6b55.png)

**Comment by TheNexusAvenger** [comment]
> I just found that print calls within the functions I'm testing aren't being displayed in either the output window or the test output window. Is there a way to enable it?

You should see the last 2 comments on https://github.com/TheNexusAvenger/Nexus-Unit-Testing/pull/2 about this, including the recommended way about this. As mentioned there, this is a docs issue.

> Also, a minor problem: print calls within the test code are being displayed, but the first line is obscured under the test name heading:

I mentioned this a few comments ago. This should be filed as an issue for the plugin itself.
https://github.com/thenexusavenger/nexus-unit-testing-plugin/issues

**Comment by psdillon** [comment]
> You should see the last 2 comments on #2 about this, including the recommended way about this. As mentioned there, this is a docs issue.

It's gone over my head. :)  I will re-read when I've learnt a bit more about Lua and Roblox.

> I mentioned this a few comments ago

Apologies, you did.  It's strange that when I was running it yesterday it did not have the problem.

> This should be filed as an issue for the plugin itself

Done.

Thanks.
