### ISSUE TITLE
Individual tests do not show  output

### ISSUE THREAD

**Issue by ok-nick** [TheNexusAvenger/Nexus-Unit-Testing#7]
Opening the ModuleScript tab will show the output for every test it contains. Opening an individual test tab will always say `No Output`, no matter if it errors or prints. I'm currently using TestEZ.

**Comment by TheNexusAvenger** [comment]
TestEZ's implementation is very limited currently. Right now, all it does is run the test runner and create the subtests *after* all the tests complete. This means there is no per-test capture of the output. The only way around this as far as I know is a custom TestEZ runner, which I don't plan on implementing right now. Pull requests are open for that type of functionality.

**Comment by TheNexusAvenger** [comment]
This is now addressed in the master branch of both Nexus Unit Testing and Nexus Unit Testing Plugin with the offer of some funding to address it. TestEZ was *finally* updated and *finally* is properly integrated. The following screenshot is an example of a modified test of Roact with a lot of extra print statements, error, skips, and FIXMEs:
![image](https://user-images.githubusercontent.com/13441476/170556834-1df4aede-dfa6-46d1-8e9f-8abfc0278383.png)

Once the branch is released as V.2.3.0, I will close this issue.
