### ISSUE TITLE
Horizontal scrolling bar for test window

### ISSUE THREAD

**Issue by ok-nick** [TheNexusAvenger/Nexus-Unit-Testing#8]
In a small plugin window, it is currently impossible to read the entire test message without popping out the window and resizing it, or getting a better view by clicking on the tab.

![image](https://user-images.githubusercontent.com/25470747/115489484-42531780-a22a-11eb-9a63-5f60752f7649.png)

**Comment by TheNexusAvenger** [comment]
This is a valid feature request, but for the wrong project. See:
https://github.com/TheNexusAvenger/Nexus-Unit-Testing-Plugin
