### ISSUE TITLE
Add option to kill running tests in plugin

### ISSUE THREAD

**Issue by daftcube** [TheNexusAvenger/Nexus-Unit-Testing#9]
Because I have a tendency to be clueless, I have run into several instances where the code my unit testing code is evaluating enters an infinite loop. It would be nice for the testing plugin to have a feature to kill any running tests.

I'm using TestEZ, if that matters.

**Comment by TheNexusAvenger** [comment]
This feature isn't really practical to implement. It is possible, but only in cases where you index a global variable, like `game`, `wait`, or `coroutine`, and those indexes would become slower. There isn't anything that can be done if you were stuck in a `WaitForChild` or infinite loop with only local variables. I've looked into it before, and the limitations made it impractical: https://devforum.roblox.com/t/killing-a-loadstring-externally-mid-execution/13780/12
